spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/userservice}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}

  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}